### ISSUE TITLE
Grants Document

### ISSUE THREAD

**Issue by lazaridiscom** [w3f/Web3-collaboration#84]
I visited

https://github.com/w3f/Web3-collaboration/blob/master/grants/grants.md

and got a little bit overwhelmed by the information and process.

## Problem A

It would help to split the document into two:

* web3 Foundation OSS Grants
* web3 Foundation Event Sponsorship

## Problem B

The described process shreds nearly immediately my motivation (i did not even manage to read through). My estimation is that going through this process would render me nearly inoperative for days or weeks (yes, this means that your process would freak me out, like e.g. a bank-loan application or similar stuff).

The same will most possibly happen to any "free thinking minds" - and be assured that ParityTech need "free thinkers" to master the implementation of such a bombastic system.

(No need to justify anything. Either use the feedback, or ignore it. Both are fine to me.)

**Comment by EdwardAThomson** [comment]
Thanks for the feedback. There will be a cut down version of the process on the new version of website. The page evolves as the needs of the foundation and the community change. Events could be reasonably split from software, that has been discussed at length internally.

The grants page needs to cover many aspects in order to ensure quality applications. Some points of information that missed in previous versions of the page came up as questions, so we often decided to make those points clearer in the document.

We don't assume that everyone who applies will be a developer so we've opted for making the details explicit such that anyone can follow the guide to create an application. Fortunately, we have had good signal-to-noise in the applications received so far.

Note that the grants are funded by the Web3 Foundation (not Parity Technologies).

**Comment by lazaridiscom** [comment]
> No need to justify anything. 

See, I wrote this to avoid seeing justifications which cannot justify the unjustifiable.

Fix this (public visible, now) mess. It takes an estimated 30 min.

> Note that the grants are funded by the Web3 Foundation (not Parity Technologies).

Yeah, yeah. And I'm a frog!
